# Generated by Django 3.2.9 on 2021-11-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview',
            field=models.FileField(default='xd.jpg', upload_to='books/', verbose_name='Adjunto del libro'),
            preserve_default=False,
        ),
    ]
