# Generated by Django 3.2.9 on 2021-11-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211112_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
